
# tap repositories and their packages

tap homebrew/core
brew chezmoi
brew gdbm
brew mas
brew mpdecimal
brew openssl@1.1
brew python@3.9
brew readline
brew sqlite
brew xz

tap homebrew/bundle

tap homebrew/cask
cask alfred
cask brave-browser
cask firefox
cask slack

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836   GarageBand  (10.4.2)
appstore 408981434   iMovie      (10.2.2)
appstore 409183694   Keynote     (10.3.9)
appstore 409203825   Numbers     (10.3.9)
appstore 409201541   Pages       (10.3.9)
