
# tap repositories and their packages

tap homebrew/core
brew aom
brew autoconf
brew bdw-gc
brew c-ares
brew cairo
brew chezmoi
brew cmake
brew docbook
brew docbook-xsl
brew fd
brew fish
brew fontconfig
brew freetype
brew fribidi
brew gcc
brew gd
brew gdbm
brew gdk-pixbuf
brew gettext
brew ghostscript
brew glib
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnuplot
brew gnutls
brew gobject-introspection
brew graphite2
brew grep
brew guile
brew harfbuzz
brew icu4c
brew imagemagick
brew imath
brew isl
brew jansson
brew jbig2dec
brew jemalloc
brew jpeg
brew libcerf
brew libde265
brew libev
brew libevent
brew libffi
brew libgccjit
brew libheif
brew libidn
brew libidn2
brew liblqr
brew libmpc
brew libomp
brew libpng
brew libpthread-stubs
brew librsvg
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libuv
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lua
brew luajit-openresty
brew luv
brew lzo
brew m4
brew mas
brew mpdecimal
brew mpfr
brew msgpack
brew ncurses
brew neofetch
brew neovim
brew nettle
brew nghttp2
brew openexr
brew openjpeg
brew openssl@1.1
brew p11-kit
brew pango
brew pcre
brew pcre2
brew pixman
brew pkg-config
brew python@3.9
brew qt@5
brew readline
brew ripgrep
brew rust
brew screenresolution
brew shared-mime-info
brew sqlite
brew starship
brew texinfo
brew tree-sitter
brew unbound
brew unibilium
brew webp
brew x265
brew xmlto
brew xorgproto
brew xz
brew zlib
brew zstd

tap homebrew/bundle

tap homebrew/cask-fonts
cask font-fira-code-nerd-font
cask font-hack
cask font-hack-nerd-font
cask font-jetbrains-mono
cask font-jetbrains-mono-nerd-font
cask font-overpass

tap homebrew/services

tap homebrew/cask
cask alfred
cask brave-browser
cask discord
cask docker
cask firefox
cask fly
cask hammerspoon
cask kitty
cask rectangle
cask signal
cask slack
cask ukelele
cask zoom

tap cmacrae/formulae

tap d12frosted/emacs-plus
brew emacs-plus@28 --with-native-comp --with-modern-sexy-v1-icon

tap koekeishiya/formulae
brew skhd

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 682658836   GarageBand  (10.4.2)
appstore 408981434   iMovie      (10.2.2)
appstore 409183694   Keynote     (10.3.9)
appstore 409203825   Numbers     (10.3.9)
appstore 409201541   Pages       (10.3.9)
