#!/bin/bash
# Gets battery percentage and charging status from acpi and echos for i3 blocks
PERCENT=`cat /sys/class/power_supply/BAT0/capacity`
CHARGE=`cat /sys/class/power_supply/BAT0/status`

if [ $CHARGE == "Discharging" ]; then
	STAT='↓'
else
	STAT='↑'
fi

if [ $PERCENT -lt 10 ]; then
	dunstify "Plug in your charger!"
fi

echo $PERCENT $STAT #full
echo $PERCENT $STAT #short
